version: '3'

services:
  web:
    image: AWS_ECR_REPOSITORY_URL_FULL
    command: python function.py
    environment: 
      # 本体のAPIのKEY
      - CON_KEY
      - CON_KEY_SEC
      - ACC_KEY
      - ACC_KEY_SEC
      - QUERY=#休園中の動物園水族館
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: zoo_aqua
        awslogs-stream-prefix: zoo_aqua